baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LonerHermitNEET'
theme = 'huge-book'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'


  # (Optional, default January 2, 2006) Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
